version: "2"
services:
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_DATABASE: easyappointments
      MYSQL_ROOT_PASSWORD: hellodocker
    networks:
      - app

  www:
    image: altrgeek/easyappointments:latest
    container_name: easyappointments
    environment:
      DB_NAME: easyappointments
      DB_PASSWORD: hellodocker
      BASE_URL: http://localhost:8888
    ports:
      - 8888:8888
    networks:
      - app

networks:
  app:
    driver: bridge
